apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.jobservice" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "harbor.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: jobservice
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "harbor.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobservice
