{{ if .Values.trivy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.trivy" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "harbor.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: trivy
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "harbor.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: api-server
      protocol: TCP
      port: 8080
      targetPort: api-server
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: trivy
{{ end }}
