apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.registry" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "harbor.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "harbor.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
