{{- if eq .Values.service.type "Ingress" }}
{{- if eq .Values.service.ingress.controller "gce" }}
  {{- $_ := set . "portal_path" "/*" -}}
  {{- $_ := set . "api_path" "/api/*" -}}
  {{- $_ := set . "service_path" "/service/*" -}}
  {{- $_ := set . "v2_path" "/v2/*" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/*" -}}
  {{- $_ := set . "controller_path" "/c/*" -}}
{{- else if eq .Values.service.ingress.controller "ncp" }}
  {{- $_ := set . "portal_path" "/" -}}
  {{- $_ := set . "api_path" "/api/.*" -}}
  {{- $_ := set . "service_path" "/service/.*" -}}
  {{- $_ := set . "v2_path" "/v2/.*" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/.*" -}}
  {{- $_ := set . "controller_path" "/c/.*" -}}
{{- else }}
  {{- $_ := set . "portal_path" "/" -}}
  {{- $_ := set . "api_path" "/api/" -}}
  {{- $_ := set . "service_path" "/service/" -}}
  {{- $_ := set . "v2_path" "/v2/" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/" -}}
  {{- $_ := set . "controller_path" "/c/" -}}
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "harbor.ingress" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .Values.service.ingress.annotations }}
   {{- toYaml .Values.service.ingress.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.tls.enabled }}
  tls:
    {{- if .Values.service.tls.secretName }}
    - secretName: {{ .Values.service.tls.secretName }}
    {{- else }}
    - secretName: {{ include "harbor.ingress" . }}
    {{- end }}
      {{- if .Values.service.ingress.hosts.core }}
      hosts:
        - {{ .Values.service.ingress.hosts.core }}
      {{- end }}
    {{- if .Values.notary.enabled }}
    {{- if .Values.service.tls.notarySecretName }}
    - secretName: {{ .Values.service.tls.notarySecretName | quote }}
    {{- else if .Values.service.tls.secretName }}
    - secretName: {{ .Values.service.tls.secretName | quote }}
    {{- else }}
    - secretName: {{ include "harbor.ingress" . | quote }}
    {{- end }}
      {{- if .Values.service.ingress.hosts.notary }}
      hosts:
        - {{ .Values.service.ingress.hosts.notary }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.service.ingress.controller "ncp" }}
  backend:
    serviceName: {{ include "harbor.portal" . }}
    servicePort: http
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .portal_path }}
            backend:
              serviceName: {{ include "harbor.portal" . }}
              servicePort: http
          - path: {{ .api_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .service_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .v2_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .chartrepo_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .controller_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
      {{- if .Values.service.ingress.hosts.core }}
      host: {{ .Values.service.ingress.hosts.core }}
      {{- end }}
    {{- if .Values.notary.enabled }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "harbor.notary-server" . }}
              servicePort: notary-server
      {{- if .Values.service.ingress.hosts.notary }}
      host: {{ .Values.service.ingress.hosts.notary }}
      {{- end }}
    {{- end }}
{{- end }}
